### FRONTEND
FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
COPY . .
RUN npm install
RUN npm run build

### NGINX
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/conf.d/nginx.conf.template
COPY nginx-env.sh /nginx-env.sh
RUN chmod +x nginx-env.sh
CMD ["sh", "nginx-env.sh"]

EXPOSE 80
