### FRONTEND ###
FROM ubuntu:22.04

ENV NVM_DIR=/root/.nvm \
    NODE_VERSION=18.17.0

RUN apt-get update && \
    apt-get install -y curl build-essential libssl-dev ca-certificates git && \
    rm -rf /var/lib/apt/lists/*

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash && \
    . "$NVM_DIR/nvm.sh" && \
    nvm install $NODE_VERSION && \
    nvm alias default $NODE_VERSION && \
    nvm use default && \
    npm install -g npm@9.6.7

ENV NODE_PATH=$NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules \
    PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

WORKDIR /app

COPY /frontend .

RUN corepack enable
RUN npm install

EXPOSE 3000

CMD ["yarn", "start"]
