# APP SECRETS
apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
# echo -n 'postgres' | base64
# echo -n 'cG9zdGdyZXM=' | base64 --decode
data:
  db-user: cG9zdGdyZXM=
  db-password: cG9zdGdyZXM=
